# Esercizio 1

**Indicizzazione booleana**

In [31]:
# Creare un vettore con tutti i numeri primi da 0 a 20

# Importiamo il modulo NumPy
import numpy as np

def is_prime(n):
    """ Ritorna T se il numero è primo, F altrimenti
    
    Parametri:
        n (int)

    Output:
        TRUE se 'n' è primo, FALSE altrimenti
    """
    if (n == 0) or (n == 1):
        return False
    elif (n == 2) or (n == 3) or (n == 5) or (n == 7):
        return True
    else:

        for i in range(2,int(n/2)+1):

            if (n % i == 0):
                return False
        
    return True

# Creiamo il vettore 'prime_array' a partire da una lista
prime_list = [x for x in range(1,21) if is_prime(x)]
prime_array = np.array(prime_list)

print(f"L'array è: {prime_array}")

L'array è: [ 2  3  5  7 11 13 17 19]


In [32]:
# Utilizzando un test logico, selezionare tutte le voci del vettore maggiori di 10

print(f"Gli elementi del vettore maggiori di 10 sono: {prime_array[prime_array > 10]}")

Gli elementi del vettore maggiori di 10 sono: [11 13 17 19]


In [33]:
# Utilizzando un test logico, selezionare tutti i numeri primi pari dal vettore

print(f"I numeri primi pari contenuti nel vettore sono: {prime_array[(prime_array % 2) == 0]}")

I numeri primi pari contenuti nel vettore sono: [2]


# Esercizio 2

**Operazioni su array**

In [34]:
# Creiamo l'array 'a' 2D

a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8],
              [9,10]])

print(f"L'array 'a' è: \n{a}")

L'array 'a' è: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [35]:
# Creiamo l'array 'b', contenente la seconda e quarta riga di 'a'

b = a[1::2,:]
print(f"L'array 'b' è: \n{b}")

# Creiamo l'array 'c', contenente la terza riga di 'a'

c = a[2,:]
print(f"L'array 'c' è: \n{c}")

L'array 'b' è: 
[[3 4]
 [7 8]]
L'array 'c' è: 
[5 6]


In [36]:
# Dividiamo ogni colonna dell'array 'a', elemento per elemento, con l'array 'c'

print(f"Il risultato della divisione tra l'array 'a' e l'array 'c' e: \n{a / c}")

Il risultato della divisione tra l'array 'a' e l'array 'c' e: 
[[0.2        0.33333333]
 [0.6        0.66666667]
 [1.         1.        ]
 [1.4        1.33333333]
 [1.8        1.66666667]]


# Esercizio 3

**Selezionare il numero più vicino a 0.5 in un array casuale**

In [37]:
# Generiamo un array 10 x 3 e popoliamolo con numeri casuali compresi nell'intervallo (0,1)

# Utilizziamo la funzione 'random.rand()' integrata nel modulo NumPy
random_array = np.round(np.random.rand(10,3),2)
print(f"L'array casuale generato è: \n{random_array}")

L'array casuale generato è: 
[[0.34 0.31 0.3 ]
 [0.59 0.66 0.05]
 [0.54 0.14 0.69]
 [0.52 0.01 0.94]
 [0.66 0.77 0.49]
 [0.13 0.62 0.51]
 [0.79 0.37 0.19]
 [0.86 0.46 0.71]
 [0.99 0.3  0.38]
 [0.71 0.41 0.5 ]]


In [38]:
# Dobbiamo ora selezionare, per ogni riga, l'elemento più vicino a 0.5 aiutandoci col fancy indexing

# Creiamo i vettori su cui 'scorreremo' le righe e le colonne della matrice
lines = np.array(range(10))
columns = np.array(range(3))

# Importiamo il modulo 'math' per il valore assoluto
import math

# Scorriamo sulle linee
for i in lines:
    # In 'index_counter' sarà salvato l'indice di colonna del valore ricercato
    index_counter = 0
    # 'diff_btw' contiene la differenza tra 0.5 e il valore in posizione [i,j]
    diff_btw = round(abs(0.5 - random_array[i,0]),4)

    # Scorriamo sulle colonne
    for j in columns:

        if j != 0:

            # Se troviamo un valore più vicino modifichiamo 'index_counter' e 'diff_btw'
            if (diff_btw > abs(0.5 - random_array[i,j])):
                index_counter = j
                diff_btw = round(abs(0.5 - random_array[i,j]),4)
            
    print(f"Il valore più vicino a 0.5 a riga {i} è {random_array[i,index_counter]} con una differenza di {diff_btw}")

Il valore più vicino a 0.5 a riga 0 è 0.34 con una differenza di 0.16
Il valore più vicino a 0.5 a riga 1 è 0.59 con una differenza di 0.09
Il valore più vicino a 0.5 a riga 2 è 0.54 con una differenza di 0.04
Il valore più vicino a 0.5 a riga 3 è 0.52 con una differenza di 0.02
Il valore più vicino a 0.5 a riga 4 è 0.49 con una differenza di 0.01
Il valore più vicino a 0.5 a riga 5 è 0.51 con una differenza di 0.01
Il valore più vicino a 0.5 a riga 6 è 0.37 con una differenza di 0.13
Il valore più vicino a 0.5 a riga 7 è 0.46 con una differenza di 0.04
Il valore più vicino a 0.5 a riga 8 è 0.38 con una differenza di 0.12
Il valore più vicino a 0.5 a riga 9 è 0.5 con una differenza di 0.0


# Esercizio 4

**Analisi della Frequenza Cardiaca con NumPy**

In [39]:
# Creiamo l'array che contiene i calori della frequenza cardiaca partendo da una lista

fitbit_list = [68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70]
fitbit_array = np.array(fitbit_list)

print(f"L'array delle frequenze cardiache è: \n{fitbit_array}")

L'array delle frequenze cardiache è: 
[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]


In [40]:
# Troviamo il valore minimo attraverso la funzione 'Min'

print(f"La frequenza cardiaca minima è {np.min(fitbit_array)}")

# Troviamo il valore massimo attraverso la funzione 'Max'

print(f"La frequenza cardiaca massima è {np.max(fitbit_array)}")

La frequenza cardiaca minima è 60
La frequenza cardiaca massima è 164


In [41]:
# Calcoliamo la percentuale di letture effettuate mentre si sta facendo esercizio fisico (frequenza cardiaca sopra a 120)

# Creiamo l'array 'obs_boolean' per verificare quali frequenze sono maggiori a 120
obs_boolean = fitbit_array > 120

# Calcoliamo la percentuale con la funzione 'mean()' del modulo NumPy
print(f"Percentuale di osservazioni sopra 120 bpm: {np.round(np.mean(obs_boolean) * 100,2)}%")

Percentuale di osservazioni sopra 120 bpm: 52.38%


# Esercizio 5

**Manipolazione di vettori**

In [42]:
# Creiamo il vettore degli stipendi e calcoliamo la somma

salary = np.array([50_000, 105_250, 55_000, 89_000])
first_sum = np.sum(salary)

print(f"Il costo totale del personale è {first_sum}$")

Il costo totale del personale è 299250$


In [43]:
# Aumentiamo del 15% lo stipendio più alto (maledetto CEO)

# Calcoliamo l'incremento del 15% e sommiamolo allo stipendio del CEO
increase = (salary[1] * 15) / 100
salary[1] += increase

print(f"Il nuovo stipendio del CEO è {salary[1]}$")
print(f"Il nuovo array è: {salary}")

Il nuovo stipendio del CEO è 121037$
Il nuovo array è: [ 50000 121037  55000  89000]


Il problema nel codice precdente è che NumPy usa il tipo predefinito *int64* per gli array interi, quindi quando sommiamo il 15% al salario del CEO, il risultato viene troncato a un numero intero.

In [44]:
# Ripetiamo il punto precedente utilizzando la funzione 'dtype'

# Creiamo il vettore degli stipendi e calcoliamo la somma
salary_fl = np.array([50_000, 105_250, 55_000, 89_000], dtype=np.float64)

# Calcoliamo l'incremento del 15% e sommiamolo allo stipendio del CEO
increase = (salary_fl[1] * 15) / 100
salary_fl[1] += increase

print(f"Il nuovo stipendio del CEO è {salary_fl[1]}$")
print(f"Il nuovo array è: {salary_fl}")

Il nuovo stipendio del CEO è 121037.5$
Il nuovo array è: [ 50000.  121037.5  55000.   89000. ]


In [45]:
# Aumentiamo ora lo stipendio del primo impiegato del 20%

increase = (salary_fl[0] * 20) / 100
salary_fl[0] += increase

print(f"Il nuovo stipendio del dipendente è {salary_fl[0]}$")
print(f"Il nuovo array è: {salary_fl}")

Il nuovo stipendio del dipendente è 60000.0$
Il nuovo array è: [ 60000.  121037.5  55000.   89000. ]


In [46]:
# Aumentiamo gli altri due stipendi del 10%

for i in range(2,4):
    increase = (salary_fl[i] * 10) / 100
    salary_fl[i] += increase

    print(f"Il nuovo stipendio del dipendente {i} è {salary_fl[i]}$")

print(f"Il nuovo array è: {salary_fl}")

Il nuovo stipendio del dipendente 2 è 60500.0$
Il nuovo stipendio del dipendente 3 è 97900.0$
Il nuovo array è: [ 60000.  121037.5  60500.   97900. ]


In [47]:
# Calcoliamo ora l'aumento totale degli stipendi

second_sum = np.sum(salary_fl)

print(f"La differenza è {second_sum - first_sum}$")

La differenza è 40187.5$


# Esercizio 6

**Valori di CO2**

In [48]:
# Carichiamo il file sulle emissioni di CO2

import numpy as np

# Generazione di 200 valori casuali di emissioni di CO2 in tonnellate per anno 
# Supponiamo emissioni tra 4 e 20 tonnellate per persona 
co2_emissions = np.round(np.random.uniform(4, 20, 200), 2)

# Nome del file di output
output_file = "/home/edo/Scrivania/Programmazione/Laboratorio di Programmazione/-ProgrammingLab2/Lezione_2/CO2_emissioni.txt"

# Salvataggio su file
np.savetxt(output_file, co2_emissions, fmt="%.2f")

print(f"Il path del file 'CO2_emissioni.txt' è {output_file}")


Il path del file 'CO2_emissioni.txt' è /home/edo/Scrivania/Programmazione/Laboratorio di Programmazione/-ProgrammingLab2/Lezione_2/CO2_emissioni.txt


In [49]:
# Calcoliamo quanti valori ci CO2 sono sopra la soglia di 18 tonnellate per anno ed il loro valore medio

# Utilizziano la funzione 'mean' del modulo NumPy
print(f"La media dei valori sopra le 18 tonnellate è {np.round(np.mean(co2_emissions[co2_emissions > 18]), 2)}")

La media dei valori sopra le 18 tonnellate è 19.0


In [50]:
# Calcolare la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

# Utilizziano la funzione 'mean' e 'sum' del modulo NumPy
print(f"La frazione totale di emissione sopra la soglia è {np.round(np.sum(co2_emissions[co2_emissions > 18]) / np.sum(co2_emissions), 4)}")

La frazione totale di emissione sopra la soglia è 0.2215
