# Esercizio 1

**Indicizzazione booleana**

In [31]:
# Creare un vettore con tutti i numeri primi da 0 a 20

# Importiamo il modulo NumPy
import numpy as np

def is_prime(n):
    """ Ritorna T se il numero è primo, F altrimenti
    
    Parametri:
        n (int)

    Output:
        TRUE se 'n' è primo, FALSE altrimenti
    """
    if (n == 0) or (n == 1):
        return False
    elif (n == 2) or (n == 3) or (n == 5) or (n == 7):
        return True
    else:

        for i in range(2,int(n/2)+1):

            if (n % i == 0):
                return False
        
    return True

# Creiamo il vettore 'prime_array' a partire da una lista
prime_list = [x for x in range(1,21) if is_prime(x)]
prime_array = np.array(prime_list)

print(f"L'array è: {prime_array}")

L'array è: [ 2  3  5  7 11 13 17 19]


In [32]:
# Utilizzando un test logico, selezionare tutte le voci del vettore maggiori di 10

print(f"Gli elementi del vettore maggiori di 10 sono: {prime_array[prime_array > 10]}")

Gli elementi del vettore maggiori di 10 sono: [11 13 17 19]


In [33]:
# Utilizzando un test logico, selezionare tutti i numeri primi pari dal vettore

print(f"I numeri primi pari contenuti nel vettore sono: {prime_array[(prime_array % 2) == 0]}")

I numeri primi pari contenuti nel vettore sono: [2]


# Esercizio 2

**Operazioni su array**

In [34]:
# Creiamo l'array 'a' 2D

a = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8],
              [9,10]])

print(f"L'array 'a' è: \n{a}")

L'array 'a' è: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [35]:
# Creiamo l'array 'b', contenente la seconda e quarta riga di 'a'

b = a[1::2,:]
print(f"L'array 'b' è: \n{b}")

# Creiamo l'array 'c', contenente la terza riga di 'a'

c = a[2,:]
print(f"L'array 'c' è: \n{c}")

L'array 'b' è: 
[[3 4]
 [7 8]]
L'array 'c' è: 
[5 6]


In [36]:
# Dividiamo ogni colonna dell'array 'a', elemento per elemento, con l'array 'c'

print(f"Il risultato della divisione tra l'array 'a' e l'array 'c' e: \n{a / c}")

Il risultato della divisione tra l'array 'a' e l'array 'c' e: 
[[0.2        0.33333333]
 [0.6        0.66666667]
 [1.         1.        ]
 [1.4        1.33333333]
 [1.8        1.66666667]]


# Esercizio 3

**Selezionare il numero più vicino a 0.5 in un array casuale**

In [37]:
# Generiamo un array 10 x 3 e popoliamolo con numeri casuali compresi nell'intervallo (0,1)

# Utilizziamo la funzione 'random.rand()' integrata nel modulo NumPy
random_array = np.round(np.random.rand(10,3),2)
print(f"L'array casuale generato è: \n{random_array}")

L'array casuale generato è: 
[[0.34 0.31 0.3 ]
 [0.59 0.66 0.05]
 [0.54 0.14 0.69]
 [0.52 0.01 0.94]
 [0.66 0.77 0.49]
 [0.13 0.62 0.51]
 [0.79 0.37 0.19]
 [0.86 0.46 0.71]
 [0.99 0.3  0.38]
 [0.71 0.41 0.5 ]]


In [38]:
# Dobbiamo ora selezionare, per ogni riga, l'elemento più vicino a 0.5 aiutandoci col fancy indexing

# Creiamo i vettori su cui 'scorreremo' le righe e le colonne della matrice
lines = np.array(range(10))
columns = np.array(range(3))

# Importiamo il modulo 'math' per il valore assoluto
import math

# Scorriamo sulle linee
for i in lines:
    # In 'index_counter' sarà salvato l'indice di colonna del valore ricercato
    index_counter = 0
    # 'diff_btw' contiene la differenza tra 0.5 e il valore in posizione [i,j]
    diff_btw = round(abs(0.5 - random_array[i,0]),4)

    # Scorriamo sulle colonne
    for j in columns:

        if j != 0:

            # Se troviamo un valore più vicino modifichiamo 'index_counter' e 'diff_btw'
            if (diff_btw > abs(0.5 - random_array[i,j])):
                index_counter = j
                diff_btw = round(abs(0.5 - random_array[i,j]),4)
            
    print(f"Il valore più vicino a 0.5 a riga {i} è {random_array[i,index_counter]} con una differenza di {diff_btw}")

Il valore più vicino a 0.5 a riga 0 è 0.34 con una differenza di 0.16
Il valore più vicino a 0.5 a riga 1 è 0.59 con una differenza di 0.09
Il valore più vicino a 0.5 a riga 2 è 0.54 con una differenza di 0.04
Il valore più vicino a 0.5 a riga 3 è 0.52 con una differenza di 0.02
Il valore più vicino a 0.5 a riga 4 è 0.49 con una differenza di 0.01
Il valore più vicino a 0.5 a riga 5 è 0.51 con una differenza di 0.01
Il valore più vicino a 0.5 a riga 6 è 0.37 con una differenza di 0.13
Il valore più vicino a 0.5 a riga 7 è 0.46 con una differenza di 0.04
Il valore più vicino a 0.5 a riga 8 è 0.38 con una differenza di 0.12
Il valore più vicino a 0.5 a riga 9 è 0.5 con una differenza di 0.0


# Esercizio 4

**Analisi della Frequenza Cardiaca con NumPy**

In [39]:
# Creiamo l'array che contiene i calori della frequenza cardiaca partendo da una lista

fitbit_list = [68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70]
fitbit_array = np.array(fitbit_list)

print(f"L'array delle frequenze cardiache è: \n{fitbit_array}")

L'array delle frequenze cardiache è: 
[ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]


In [40]:
# Troviamo il valore minimo attraverso la funzione 'Min'

print(f"La frequenza cardiaca minima è {np.min(fitbit_array)}")

# Troviamo il valore massimo attraverso la funzione 'Max'

print(f"La frequenza cardiaca massima è {np.max(fitbit_array)}")

La frequenza cardiaca minima è 60
La frequenza cardiaca massima è 164


In [41]:
# Calcoliamo la percentuale di letture effettuate mentre si sta facendo esercizio fisico (frequenza cardiaca sopra a 120)

# Creiamo l'array 'obs_boolean' per verificare quali frequenze sono maggiori a 120
obs_boolean = fitbit_array > 120

# Calcoliamo la percentuale con la funzione 'mean()' del modulo NumPy
print(f"Percentuale di osservazioni sopra 120 bpm: {np.round(np.mean(obs_boolean) * 100,2)}%")

Percentuale di osservazioni sopra 120 bpm: 52.38%


# Esercizio 5

**Manipolazione di vettori**

In [42]:
# Creiamo il vettore degli stipendi e calcoliamo la somma

salary = np.array([50_000, 105_250, 55_000, 89_000])
first_sum = np.sum(salary)

print(f"Il costo totale del personale è {first_sum}$")

Il costo totale del personale è 299250$


In [43]:
# Aumentiamo del 15% lo stipendio più alto (maledetto CEO)

# Calcoliamo l'incremento del 15% e sommiamolo allo stipendio del CEO
increase = (salary[1] * 15) / 100
salary[1] += increase

print(f"Il nuovo stipendio del CEO è {salary[1]}$")
print(f"Il nuovo array è: {salary}")

Il nuovo stipendio del CEO è 121037$
Il nuovo array è: [ 50000 121037  55000  89000]


Il problema nel codice precdente è che NumPy usa il tipo predefinito *int64* per gli array interi, quindi quando sommiamo il 15% al salario del CEO, il risultato viene troncato a un numero intero.

In [44]:
# Ripetiamo il punto precedente utilizzando la funzione 'dtype'

# Creiamo il vettore degli stipendi e calcoliamo la somma
salary_fl = np.array([50_000, 105_250, 55_000, 89_000], dtype=np.float64)

# Calcoliamo l'incremento del 15% e sommiamolo allo stipendio del CEO
increase = (salary_fl[1] * 15) / 100
salary_fl[1] += increase

print(f"Il nuovo stipendio del CEO è {salary_fl[1]}$")
print(f"Il nuovo array è: {salary_fl}")

Il nuovo stipendio del CEO è 121037.5$
Il nuovo array è: [ 50000.  121037.5  55000.   89000. ]


In [45]:
# Aumentiamo ora lo stipendio del primo impiegato del 20%

increase = (salary_fl[0] * 20) / 100
salary_fl[0] += increase

print(f"Il nuovo stipendio del dipendente è {salary_fl[0]}$")
print(f"Il nuovo array è: {salary_fl}")

Il nuovo stipendio del dipendente è 60000.0$
Il nuovo array è: [ 60000.  121037.5  55000.   89000. ]


In [46]:
# Aumentiamo gli altri due stipendi del 10%

for i in range(2,4):
    increase = (salary_fl[i] * 10) / 100
    salary_fl[i] += increase

    print(f"Il nuovo stipendio del dipendente {i} è {salary_fl[i]}$")

print(f"Il nuovo array è: {salary_fl}")

Il nuovo stipendio del dipendente 2 è 60500.0$
Il nuovo stipendio del dipendente 3 è 97900.0$
Il nuovo array è: [ 60000.  121037.5  60500.   97900. ]


In [47]:
# Calcoliamo ora l'aumento totale degli stipendi

second_sum = np.sum(salary_fl)

print(f"La differenza è {second_sum - first_sum}$")

La differenza è 40187.5$


# Esercizio 6

**Valori di CO2**

In [48]:
# Carichiamo il file sulle emissioni di CO2

import numpy as np

# Generazione di 200 valori casuali di emissioni di CO2 in tonnellate per anno 
# Supponiamo emissioni tra 4 e 20 tonnellate per persona 
co2_emissions = np.round(np.random.uniform(4, 20, 200), 2)

# Nome del file di output
output_file = "/home/edo/Scrivania/Programmazione/Laboratorio di Programmazione/-ProgrammingLab2/Lezione_2/CO2_emissioni.txt"

# Salvataggio su file
np.savetxt(output_file, co2_emissions, fmt="%.2f")

print(f"Il path del file 'CO2_emissioni.txt' è {output_file}")


Il path del file 'CO2_emissioni.txt' è /home/edo/Scrivania/Programmazione/Laboratorio di Programmazione/-ProgrammingLab2/Lezione_2/CO2_emissioni.txt


In [49]:
# Calcoliamo quanti valori ci CO2 sono sopra la soglia di 18 tonnellate per anno ed il loro valore medio

# Utilizziano la funzione 'mean' del modulo NumPy
print(f"La media dei valori sopra le 18 tonnellate è {np.round(np.mean(co2_emissions[co2_emissions > 18]), 2)}")

La media dei valori sopra le 18 tonnellate è 19.0


In [50]:
# Calcolare la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

# Utilizziano la funzione 'mean' e 'sum' del modulo NumPy
print(f"La frazione totale di emissione sopra la soglia è {np.round(np.sum(co2_emissions[co2_emissions > 18]) / np.sum(co2_emissions), 4)}")

La frazione totale di emissione sopra la soglia è 0.2215


# Esercizio 7

**Analisi di una matrice**

In [4]:
# Creiamo la matrice 'survey contenente età, reddito e anni di istruzione di alcuni intervistati

import numpy as np

survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])
print(f"Matrice 'sruvey': \n{survey_matrix}")

Matrice 'sruvey': 
[[   25 40000    10]
 [   32 52000    12]
 [   40 63000    14]
 [   29 47000    11]
 [   35 58000    13]]


In [14]:
# selezioniamo gli intervistati con almeno 12 anni di istruzione attraverso un test logico

print(f"La matrice contenente i dati degli intervistati con almeno 12 anni di istruzione è: \n{survey_matrix[survey_matrix[:,2] >= 12]}")

La matrice contenente i dati degli intervistati con almeno 12 anni di istruzione è: 
[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]


In [ ]:
# Selezionare i redditi degli intervistati con almeno 12 anni di istruzione in un unica riga

# Utilizziamo anche qui un test logico ma selezionando solo la seconda colonna
print(f"I redditi degli intervistati con almeno 12 anni di istruzione sono: {survey_matrix[:,1][survey_matrix[:,2] >= 12]}")

I redditi degli intervistati con almeno 12 anni di istruzione sono: [52000 63000 58000]


In [20]:
# Calcolare il reddito medio degli intervistati con almeno 12 anni di istruzione in un'unica riga

# Utilizziamo la funzione 'sum' sul test logico fatto precedentemente
print(f"Il reddito medio degli intervistati con almeno 12 anni di istruzione è {np.round(np.mean(survey_matrix[:,1][survey_matrix[:,2] >= 12]),2)}€")

Il reddito medio degli intervistati con almeno 12 anni di istruzione è 57666.67€


# Esercizio 8

**Rimpiazzare gli outliers**

In [37]:
# Generiamo l'array 'ages'

# Generiamo una classe di errori personalizzati
class Lez2Exception(Exception):
    pass

ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

# Creiamo un nuovo array in cui verranno rimosse tutte le età equivalenti a 999
new_ages = ages[ages != 999]

# Cicliamo sull'array 'new_ages' per controllare che non ci siano errori
counter = 0
for i in range(0,len(new_ages)):

    if new_ages[i] == 999:
        print(f"Elemento trovato in posizione {i}")
        counter += 1

if counter > 0:
    raise Lez2Exception(f"Errore: l'array 'new_ages' contiene l'elemento 999 {counter} volte, ma non dovrebbe")
else:
    print(f"Test passato con successo")

# Calcoliamo ora l'età del cittadino più anziano attraverso la funzione 'max' del modulo 'NumPy'
print(f"Il cittadino più anziano ha esattamente {np.max(new_ages)} anni")


Test passato con successo
Il cittadino più anziano ha esattamente 112 anni


# Esercizio 9

**Generazione random di storie**

In [65]:
# Importiamo il modulo 'rand'
import random

# Definiamo la lista 'lista_parole'
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

random_index = random.choices(range(len(lista_parole)), k=5)
print(f"Indici selezionati: {random_index}")

selected_word = [lista_parole[i] for i in random_index]
print(f"Parole selezionate: {selected_word}")

Indici selezionati: [12, 31, 29, 40, 3]
Parole selezionate: ['PROVA', 'ANNUNCIO', 'BIRILLO DA BOWLING', 'VANTAGGIO', 'APPLICAZIONE']
